# Generated by Django 2.0.6 on 2018-06-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('Prainha', 'Prainha'), ('Grumari', 'Grumari')], max_length=30)),
                ('numero', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=1)),
            ],
        ),
    ]
