# Generated by Django 2.0.6 on 2018-06-24 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloco',
            options={'verbose_name': 'Bloco', 'verbose_name_plural': 'Blocos'},
        ),
    ]
