# Generated by Django 2.0.6 on 2018-06-24 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_auto_20180624_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=4)),
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Bloco')),
            ],
        ),
        migrations.CreateModel(
            name='Morador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='apartamento',
            name='moradores',
            field=models.ManyToManyField(to='cadastro.Morador'),
        ),
    ]
